### PR TITLE
Mingle python 2 and 3 with ifdef

### PR DESCRIPTION
**Pull request by dnadeau4**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@dnadeau4 this looks great. Thanks! In the test . I think we need to add some tests for comp<rel rel<comp etc...

**Review by doutriaux1 — CHANGES_REQUESTED** [review]
@dnadeau4 I think we need to add some rl vs comp and comp vs rel tests and some == tests, just to be safe.

**Comment by dnadeau4** [comment]
@doutriaux1 please merge.

**Comment by doutriaux1** [comment]
@dnadeau4 please make sure we had tests for comptime vs reltime etc... as requested in my review. It's important to make sure this works.

**Comment by dnadeau4** [comment]
Can you make another issue for the tests?  This bug is solved.  
I did add a test between comptime vs reltime using `==` as you wanted.

**Comment by doutriaux1** [comment]
I'll add the tests myself when I get to this... Hopefully tomorrow... I would rather the branch to be complete before merging in.

**Comment by dnadeau4** [comment]
@doutriaux1 can you merge?

**Comment by doutriaux1** [comment]
I still need to add the test. Can this wait just another day?

**Comment by doutriaux1** [comment]
@dnadeau4 good thing I checked and added tests. My new tests fail. Back to to drawing board 😢

**Pull request merged**
