### PR TITLE
Condaforge

### PR DESCRIPTION
**Pull request by dnadeau4**
Convert cdat_info into cdtime_info. 
Add .travis.yml
Add couple of simple tests.

### CODE REVIEW

**Comment by dnadeau4** [comment]
https://github.com/UV-CDAT/cdtime/blob/6c699a19427cd2b79f9e28e9bb3e5768fb852415/Test/test_cdtime.py

Can you merge my test?

**Comment by dnadeau4** [comment]
I also had run_test an .travis is that PR.

**Comment by doutriaux1** [comment]
ok, i'll snatch some of this, re-opening so we do not forget.

**Comment by dnadeau4** [comment]
@doutriaux1 can you close this if not needed anymore.  I think it can be close since we use cdat_info.

**Pull request closed without merging**
