### PR TITLE
Revisit run tests

### PR DESCRIPTION
**Pull request by muryanto1**
update run_tests.py to use TestRunnerBase
update .circleci/config.yml to do py3 only if py2 fails. This will shorten test run time, if there is failure in py2 tests, we do not need to run py3.
add README.md which right now only contains status badge from Circle CI.

### CODE REVIEW

**Review by dnadeau4 — APPROVED** [review]

**Comment by doutriaux1** [comment]
Looks like you need to add testsrunner to travis

**Comment by doutriaux1** [comment]
@dnadeau4 thanks.

**Comment by dnadeau4** [comment]
I saw that, but we don't need travis anymore.

**Comment by doutriaux1** [comment]
@dnadeau4 yes I saw that you removed it. You're right it is not needed and frees resources on Travis for those who really need it.

**Pull request merged**
