### PR TITLE
Fixes extension config

### PR DESCRIPTION
**Pull request by jasonb5**
Cleans up the extension config.

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Hey @jasonb5, it was bought up by @gleckler1 that, PMP's CI tests experienced issue with this change. https://app.circleci.com/pipelines/github/PCMDI/pcmdi_metrics/479/workflows/03633821-dbaa-47ab-94ba-249399d832e6/jobs/10025?invite=true#step-106-52
I know this PR is waiting for a review from @downiec, but the conda-forge version has merged a patch of this fix. I'm wondering if this is related to PMP's CI problem?

It also looks like we need a new cdms2 build with new libnetcdf4.8.0. I will follow up with a separate email on this...

**Comment by jasonb5** [comment]
@chengzhuzhang I can take a look at that in the next couple days. It's possible this change might have something to do with it.

**Comment by jasonb5** [comment]
@chengzhuzhang @gleckler1 You can try rebuilding pcmdi_metrics again looks like cdms2 needed to be rebuild for libnetcdf 4.8.0.

**Comment by chengzhuzhang** [comment]
@jasonb5 Thanks a lot!  
@gleckler1 Hope this can fix the PMP CI test.

**Comment by lee1043** [comment]
@jasonb5 thanks for checking on this. Should I wait for this PR to be merged before rebuilding pcmdi_metrics?

**Comment by gleckler1** [comment]
@jasonb5 @lee1043 @chengzhuzhang  Thanks for looking at this.   We are still experiencing the one failure 
ci/circleci: test-linux-3.6-nompi — Your tests failed on CircleCI 

but maybe we need to wait until your PR51 is merged to expect this to work?

**Review by downiec — APPROVED** [review]
@jasonb5 Looks good, merge if you think it' ready.

**Comment by jasonb5** [comment]
@lee1043 @gleckler1  You can rebuild now the new cdms2 package came out earlier today. I'll follow up first thing tomorrow with an email.

**Comment by jasonb5** [comment]
@downiec Sounds good i'll merge. Might have some more fixes coming out soon for these libraries, i'll be making a PR for cdms2 tomorrow.

**Comment by chengzhuzhang** [comment]
Hey @jasonb5, It looks like both E3sm-diags and ARM-diags have similar issues with CDMS2 file IO. This might be relevant. Let me know if it is ready to try re-build. Thank you for taking care of this at this moment.

**Comment by lee1043** [comment]
Many thanks to @jasonb5 and all for following up on this issue. 

It looks like we still have same issue with the [PMP's circle ci test](https://app.circleci.com/pipelines/github/PCMDI/pcmdi_metrics/497/workflows/42ed6850-64d6-4a3d-ba30-d520996d119c/jobs/10419), related to CDMS2 file IO, as similar to @chengzhuzhang pointed. I see there is `libnetcdf 4.8.0` included in the circle ci testing environment. It only fails with `linux-python3.6` test envs, as @gleckler1 pointed. 

Any insight would be much appreciated. Thank you.

**Pull request merged**
